### PR TITLE
Add File Scope to SLDS Validator

### PR DESCRIPTION
**Pull request by billyma**
### What does this PR do?
Add new command, `slds.enable:scope`, to SLDS Validator

| State | Default | Description | 
| ---- | :----: | ---- | 
| TRUE | X | SLDS Validator executes for files within SFDX project | 
| FALSE | | SLDS Validator executes for any `HTML` & `CSS` files |

**SFDX project** is determined by checking if `sfdx-project.json` exists at the same level as `force-app`.

### What issues does this PR fix or reference?
Address #51

### CODE REVIEW

**Review by ambreeen — APPROVED** [review]
LGTM

**Comment by kirupa** [comment]
@billyma - this is one that the VS Code Extensions team has pinged us about. Does this expose the setting as a VS Code preference?

**Comment by billyma** [comment]
Here is the screenshot of the commands. The commands associated with this PR are at the bottom.
Screen Shot 2020-10-26 at 12 35 39 PM

**Comment by billyma** [comment]
While working on another issues, I noticed that command is not working properly. The fix is included in PR #62

**Comment by kirupa** [comment]
@billyma - can we expose this as a setting in VS Code to appear under the Salesforce node?

image

The default needs to be to only activate in SF projects for both new & existing users. Shall I file a separate ticket for this?

**Comment by billyma** [comment]
I will check what's the work on exposing it to `Extensions`. Regarding this scope, the default is `activate with SFDX projects`. User need to explicitly disable the scope for validator to run against any files.

**Comment by billyma** [comment]
@kirupa - Working on exposing it to `Extensions` Settings. Will send a PR with screenshot.

**Pull request merged**
